### ISSUE TITLE
Hunting Horn Silkbind Shockwave not counted

### ISSUE THREAD

**Issue by SeppNel** [coavins/mhrise-coavins-dps#33]
**Describe the bug**
When playing with Hunting Horn and using the new Silkbind Shockwave skill, damage is not counted for networked players (locally it works fine). The results is that the damage numbers for that player desync the more the quest goes on.

**Steps to Reproduce**
1. Use Hunting Horn with Silkbind Shockwave
2. Enter quest
3. Use Silkbind Shockwave and attack the monster (preferably with Magnificent Trio) during the quest
4. Compare damage numbers of local and network players

**Expected behavior**
Damage numbers similar for local and network players

**Comment by coavins** [comment]
Unfortunately I don't think I'm far enough in the game yet to unlock this switch skill. I will try to take a look at this when I get the chance. I'm not familiar with how this move works, but it sounds like it might be handled similar to an ailment internally, which would mean it's probably the same issue described in #21.

**Comment by coavins** [comment]
It is possible this was fixed by 5f2b3ca09fb74456524f6686fc31a1bcae9d3b69, this issue should be re-tested with the latest version.

**Comment by SeppNel** [comment]
Sadly it's not fixed. This are the damages done after quest with lastest version.
Local player (Me using Hunting Horn):
![local](https://user-images.githubusercontent.com/35899928/178112269-1b3ad270-e758-4f53-b3e2-6f6d3f43616d.png)

Network player:
![network](https://user-images.githubusercontent.com/35899928/178112277-b5e14a89-cb9b-4288-aef6-f6e398727cfe.png)

This is with a low rank monster, you can expect it to desync even more with monsters with more HP.

**Comment by coavins** [comment]
Well, thanks for double checking it. I'll have to wait until I get far enough to unlock this move before I can look into it.

**Comment by coavins** [comment]
This issue is probably related to #46. If damage is being captured accurately through `afterCalcDamage_DamageSide` *locally* but not remotely, then this is almost certainly a new problem that didn't exist before Sunbreak. I had always seen before that all players' damage had gone through this method. There must be some new technique that needs to be discovered here.

**Comment by coavins** [comment]
I'm going to close this as a duplicate of #47 just to clean up the issue list a bit
